[tool.poetry]
name = "cisco-opentelemetry-specifications"
version = "0.0.4"
description = "Cisco Opentelemetry specifications"
license = "Apache-2.0"
authors = ["Cisco Epsagon Team <support@epsagon.com>"]
readme = "README.md"
repository = "https://github.com/epsagon/cisco-otel-distribution-specifications"
